global using System;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using Microsoft.IdentityModel.Tokens;
global using Domain.Interfaces;
global using System.Linq.Expressions;
global using Domain.Enums;
global using Domain.Models;
global using System.Runtime.CompilerServices;